### ISSUE TITLE
NLC generator needs to deal with accented letters

### ISSUE THREAD

**Issue by kurtismgit** [ibm-cloud-solutions/hubot-ibmcloud-service-suggest#1]
The generator/crawler intentionally strips ascii chars outside of the range of 0-127. This was done because several BM service docs used the trademark character and in inconsistent fashion. This would cause the generator to not detect related sentences/concepts/keywords... Generally speaking this works well, however there is a BM service that has an accented letter in it's name and the generator doesn't work for this service. The service name is 'Simplicité aPaaS'.

The generator needs to allow for accented letters while still striping out the other extended ascii chars, such as ™, ©, etc...

**Comment by reicruz** [comment]
@kurtismgit 

Do we want to replace accented letters? (i.e. Simplicité = Simplicite) Or do we want to simply accepted them without them being stripped out? A simple solution would be to exclude them from the 0-127 regex match but that could get lengthy; unless we just want to include the vowels. For example: 

```
  var accentRegex = /(?![ÀÁÂÃÄàáâãäÈÉÊẼËèéêẽëÌÍÎĨÏìíîĩïÒÓÔÕÖòóôõöÙÚÛŨÜùúûũü])[^\x00-\x7F]+/g;
  return str.replace(accentRegex, '');
```

**Comment by todkap** [comment]
Where does the ascii limitation come from?

**Comment by kurtismgit** [comment]
@todkap the limitation is within our NLC training data generator (our code).  After we use AlchemyAPIs to extract keywords, concepts and relations we do string comparisons against what the service is called in the service catalog.  The extended ascii characters would through this off.  For example, the catalog might say "Watson Dialog" while the service documentation would say "Watson™ Dialog" causing the strings not to match.  So we strip out the non-base ascii characters so before comparing, in order to detect the match.

@reicruz I think in this case the generated service-data config file had "Simplicite aPaaS", but the documentation called it "Simplicité aPaaS".  So the when we did the striping the 'e' would stay in the config data while the 'é' would get stripped out.  Causing the two not to match.  I think we can simply change the service-data.json to use 'é' instead.  In which case 'é' will be stripped from both places and the string should match.  But we also need to change the config update tool to also do this stripping when comparing the existing catalog to our service-data.json file.  So that it doesn't keep adding "Simplicite aPaaS".

**Comment by todkap** [comment]
This sounds problematic longer term.  I would anticipate that we will want to support UTF-8 characters and remove HTML entities which seems less restrictive.

**Comment by kurtismgit** [comment]
Yeah, I like that suggestion.  Essentially strip out the characters which are not used in words.  For ascii that is 128-191.  That will catch the symbols that were throwing us off (®, ™, etc...) while still allowing accented characters and other UTF-8 chars through.

And @reicruz, I just remembered that our service-data config file can contain a comma separated list of doc_names.  So for the "Simplicite aPaaS" service, we just need to add "Simplicité aPaaS". to the list of doc_names.  Then recrawl only that service and update our training .csv data.
